### ISSUE TITLE
How to save the trained/best model so that I can use it later for predictions

### ISSUE THREAD

**Issue by amitk1993** [microsoft/finnts#165]
I am unable to find any functions to save/dump the trained model so that I can load/use it later for further predictions.

**Comment by mitokic** [comment]
Right now there is no formal function to create an updated forecast with previously trained models and new data. It's on the roadmap but we're prioritizing model accuracy+interpretability first. 

You can load the trained models yourself using the get_trained_models() function. Then you could manually connect those trained models with updated data after running the prep_data() function. Not super streamlined but should get you what you need in the meantime. 

https://microsoft.github.io/finnts/reference/get_trained_models.html

**Comment by amitk1993** [comment]
Hi Mitokic,

Thanks for your response. get_trained_models() returns a table of trained models but I need to save/dump best trained model as pickle/rds file... Then I can load that file and pass the unseen data for predictions.

Want to replicate the same process which we follows in model development. 

1. model training
2. save the trained model as pickle
3. load that pickle file for further predictions
