### ISSUE TITLE
TrelliscopeJS Integration

### ISSUE THREAD

**Issue by mdancho84** [microsoft/finnts#98]
Hey Michael,

I hope you are well. I wanted to give you advance notice that I will be making a new option to `timetk` and `modeltime` plotting functions to optionally allow users to use `trelliscopejs`. This is a developmental feature that helps improve the user's ability to view many time series at once.

## Trelliscope Visuals

Here's a quick example. Again this is only available in the development version. I think your users may enjoy it!

![image](https://user-images.githubusercontent.com/13734662/161429365-55a1a2cd-7aea-4ab8-a66f-9f80a9ca70ae.png)

And the code used to create it:

``` r
library(timetk)
library(tidyverse)

walmart_sales_weekly %>%
    select(id, Dept, Date, Weekly_Sales) %>%
    set_names(c("id", "dept", "date", "value")) %>%
    group_by(id, dept) %>%
    
    plot_time_series(
        date, value, 
        .trelliscope        = TRUE, 
        .facet_ncol         = 2, 
        .facet_nrow         = 2,
        .facet_strip_remove = TRUE, 
        .title              = NULL
    )
```

## More information

For more information please follow business-science/timetk#116

**Comment by mitokic** [comment]
Thanks @mdancho84 for reaching out! This looks awesome, will definitely check it out 😁
